

import org.springframework.beans.factory.annotation.AutoWired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import hello.User;
import hello.UserRepository;

@Controller //This means that this class is a Controller
@RequestMapping(path="/demo") // URL's start with /demo (after Application path)
public class MainController
{
    @Autowired // get the bean called userRepository, auto generated by Spring to handle data
    private UserRepository userRepository;

    @GetMapping(path="/add") //Map only GET requests
    public @ResponseBody String addNewUser (@RequestParam String name, @RequestParam String email)
    {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request
        User newUser = new User();
        newUser.setName(name);
        newUser.setEmail(email);
        userRepository.save(newUser);
        return "Saved";
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<User> getAllUsers()
    {
        // Returns a JSON or XML with the users
        return userRepository.findAll();
    }

}